replicaCount: 5

image:
  repository: ghcr.io/<<bank-app>>
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

nodeSelector:
  role: api

podAntiAffinity:
  enabled: true

resources: {}
