app:
  versions:
    postgres: 1683195350
  environment: dev
  host: 0.0.0.0
  port: "8080"
postgres:
  host: bank-postgres:5432
  database: bankdb
  userName: "test"
  password: "test"
  sslMode: disable
  automigrate: true